// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"LLMMock/internal/biz"
	"LLMMock/internal/conf"
	"LLMMock/internal/data"
	"LLMMock/internal/server"
	"LLMMock/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	llmMockRepo := data.NewLLMMockRepo(dataData, logger)
	llmMockUsecase := biz.NewLLMMockUsecase(llmMockRepo, logger)
	llmMockService := service.NewLLMMockService(llmMockUsecase)
	grpcServer := server.NewGRPCServer(confServer, llmMockService, logger)
	httpServer := server.NewHTTPServer(confServer, llmMockService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
