// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.6
// source: LLMMock/v1/LLM.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LLMMock_SayHello_FullMethodName      = "/LLMMock.v1.LLMMock/SayHello"
	LLMMock_SendMessage_FullMethodName   = "/LLMMock.v1.LLMMock/SendMessage"
	LLMMock_GetHistory_FullMethodName    = "/LLMMock.v1.LLMMock/GetHistory"
	LLMMock_DeleteHistory_FullMethodName = "/LLMMock.v1.LLMMock/DeleteHistory"
)

// LLMMockClient is the client API for LLMMock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMMockClient interface {
	// 根目录，验证服务是否正常运行，无需参数
	SayHello(ctx context.Context, in *RootRequest, opts ...grpc.CallOption) (*RootReply, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error)
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryReply, error)
	DeleteHistory(ctx context.Context, in *DeleteHistoryRequest, opts ...grpc.CallOption) (*DeleteHistoryReply, error)
}

type lLMMockClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMMockClient(cc grpc.ClientConnInterface) LLMMockClient {
	return &lLMMockClient{cc}
}

func (c *lLMMockClient) SayHello(ctx context.Context, in *RootRequest, opts ...grpc.CallOption) (*RootReply, error) {
	out := new(RootReply)
	err := c.cc.Invoke(ctx, LLMMock_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMMockClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error) {
	out := new(SendMessageReply)
	err := c.cc.Invoke(ctx, LLMMock_SendMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMMockClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryReply, error) {
	out := new(GetHistoryReply)
	err := c.cc.Invoke(ctx, LLMMock_GetHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMMockClient) DeleteHistory(ctx context.Context, in *DeleteHistoryRequest, opts ...grpc.CallOption) (*DeleteHistoryReply, error) {
	out := new(DeleteHistoryReply)
	err := c.cc.Invoke(ctx, LLMMock_DeleteHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMMockServer is the server API for LLMMock service.
// All implementations must embed UnimplementedLLMMockServer
// for forward compatibility
type LLMMockServer interface {
	// 根目录，验证服务是否正常运行，无需参数
	SayHello(context.Context, *RootRequest) (*RootReply, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryReply, error)
	DeleteHistory(context.Context, *DeleteHistoryRequest) (*DeleteHistoryReply, error)
	mustEmbedUnimplementedLLMMockServer()
}

// UnimplementedLLMMockServer must be embedded to have forward compatible implementations.
type UnimplementedLLMMockServer struct {
}

func (UnimplementedLLMMockServer) SayHello(context.Context, *RootRequest) (*RootReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedLLMMockServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedLLMMockServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedLLMMockServer) DeleteHistory(context.Context, *DeleteHistoryRequest) (*DeleteHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHistory not implemented")
}
func (UnimplementedLLMMockServer) mustEmbedUnimplementedLLMMockServer() {}

// UnsafeLLMMockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMMockServer will
// result in compilation errors.
type UnsafeLLMMockServer interface {
	mustEmbedUnimplementedLLMMockServer()
}

func RegisterLLMMockServer(s grpc.ServiceRegistrar, srv LLMMockServer) {
	s.RegisterService(&LLMMock_ServiceDesc, srv)
}

func _LLMMock_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMMockServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMMock_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMMockServer).SayHello(ctx, req.(*RootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMMock_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMMockServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMMock_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMMockServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMMock_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMMockServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMMock_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMMockServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMMock_DeleteHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMMockServer).DeleteHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMMock_DeleteHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMMockServer).DeleteHistory(ctx, req.(*DeleteHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMMock_ServiceDesc is the grpc.ServiceDesc for LLMMock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMMock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LLMMock.v1.LLMMock",
	HandlerType: (*LLMMockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _LLMMock_SayHello_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _LLMMock_SendMessage_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _LLMMock_GetHistory_Handler,
		},
		{
			MethodName: "DeleteHistory",
			Handler:    _LLMMock_DeleteHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "LLMMock/v1/LLM.proto",
}
